### PR TITLE
Completed css-two-column-layout | Mohamed Elmessiry

### PR DESCRIPTION
**Pull request by Mohamed-Elmessiry**
Screen Shot 2021-01-22 at 1 40 35 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
This doesn't match the example image, please revise this to match the example.

**Comment by Mohamed-Elmessiry** [comment]
Screen Shot 2021-01-23 at 3 14 00 PM

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Mohamed! The capitalization of the text in your output is incorrect as compared to the example. Make sure that the text is shown in the exact same format requested in the example.

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please update your first comment with the most up-to-date screenshot. If anything visually changes about your solution, be sure to include the picture so that the reviewers can see it.

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please update your first comment in the Pull Request with a new screenshot. You can edit the first screenshot by clicking on the three dots.

**Pull request closed without merging**
